local WindowCaps = require("controllers.window.window_capabilities")

describe("window_capabilities.lua", function()
  it("detects animation-like windows", function()
    expect(WindowCaps.isAnimationLike({ kind = "animation" })).toBeTruthy()
    expect(WindowCaps.isAnimationLike({ kind = "oam_animation" })).toBeTruthy()
    expect(WindowCaps.isAnimationLike({ kind = "static_art" })).toBeFalsy()
  end)

  it("detects static-or-animation art windows", function()
    expect(WindowCaps.isStaticOrAnimationArt({ kind = "static_art" })).toBeTruthy()
    expect(WindowCaps.isStaticOrAnimationArt({ kind = "animation" })).toBeTruthy()
    expect(WindowCaps.isStaticOrAnimationArt({ kind = "oam_animation" })).toBeTruthy()
    expect(WindowCaps.isStaticOrAnimationArt({ kind = "chr" })).toBeFalsy()
  end)

  it("detects palette window variants", function()
    expect(WindowCaps.isAnyPaletteWindow({ kind = "palette" })).toBeTruthy()
    expect(WindowCaps.isAnyPaletteWindow({ kind = "rom_palette" })).toBeTruthy()
    expect(WindowCaps.isAnyPaletteWindow({ kind = "weird", isPalette = true })).toBeTruthy()
    expect(WindowCaps.isAnyPaletteWindow({ kind = "chr" })).toBeFalsy()
    expect(WindowCaps.isRomPaletteWindow({ kind = "rom_palette" })).toBeTruthy()
    expect(WindowCaps.isGlobalPaletteWindow({ kind = "palette" })).toBeTruthy()
  end)

  it("detects chr-like and ppu/oam window kinds", function()
    expect(WindowCaps.isChrLike({ kind = "chr" })).toBeTruthy()
    expect(WindowCaps.isChrLike({ kind = "ppu_frame" })).toBeFalsy()
    expect(WindowCaps.isPpuFrame({ kind = "ppu_frame" })).toBeTruthy()
    expect(WindowCaps.isOamAnimation({ kind = "oam_animation" })).toBeTruthy()
  end)
end)
