local Badge = require("controllers.window.window_link_badge_controller")
local WM = require("controllers.window.window_controller")

describe("window_link_badge_controller.lua", function()
  it("treats palette and pattern slot pairs as compatible only across source/dest", function()
    expect(Badge.areSlotsCompatible("palette_source", "layout_palette")).toBe(true)
    expect(Badge.areSlotsCompatible("layout_palette", "palette_source")).toBe(true)
    expect(Badge.areSlotsCompatible("palette_source", "palette_source")).toBe(false)
    expect(Badge.areSlotsCompatible("pattern_source", "ppu_pattern_bg")).toBe(true)
    expect(Badge.areSlotsCompatible("pattern_source", "ppu_palette")).toBe(false)
    expect(Badge.areSlotsCompatible("ppu_pattern_bg", "ppu_pattern_sprite")).toBe(false)
  end)

  it("rejects illegal window pairs for canLinkWindows", function()
    local wm = WM.new()
    local romA = wm:createRomPaletteWindow({ title = "A" })
    local romB = wm:createRomPaletteWindow({ title = "B" })
    local pt = wm:createPatternTableWindow({ title = "PT" })
    local art = wm:createTileWindow({ title = "Art" })

    expect(Badge.canLinkWindows(romA, "palette_source", romB, "palette_source")).toBe(false)
    expect(Badge.canLinkWindows(romA, "palette_source", pt, "pattern_source")).toBe(false)
    expect(Badge.canLinkWindows(romA, "palette_source", art, "layout_palette")).toBe(true)
    expect(Badge.canLinkWindows(pt, "pattern_source", art, "layout_palette")).toBe(false)
  end)
end)
