-- sketch_canvas_gallery_rom_controller.lua
-- Assemble a gallery .nes from packed sketch windows via asm/gallery (ca65).
--
-- Pipeline:
--   1. encodeChrBankFromSketch → pad to 8KB → data/chr/slideNN.chr
--   2. encodeNametableFromSketch({ includeAttributes = true }) → data/nam/slideNN.nam
--   3. Write s/slide_meta.s (slide_count)
--   4. make -C asm/gallery → gallery.nes (copy beside ROM)

local WindowCaps = require("controllers.window.window_capabilities")
local SketchCanvasPackController = require("controllers.game_art.sketch_canvas_pack_controller")
local SketchCanvasExportController = require("controllers.game_art.sketch_canvas_export_controller")

local M = {}

M.MAX_SLIDES = 16

local function pathSep()
  return (package.config:sub(1, 1) == "\\") and "\\" or "/"
end

local function joinPath(a, b)
  a = tostring(a or "")
  b = tostring(b or "")
  if a == "" then
    return b
  end
  local sep = pathSep()
  if a:sub(-1) == "/" or a:sub(-1) == "\\" then
    return a .. b
  end
  return a .. sep .. b
end

local function fileExists(path)
  local fh = io.open(path, "rb")
  if not fh then
    return false
  end
  fh:close()
  return true
end

local function shellQuote(path)
  return "'" .. tostring(path):gsub("'", "'\\''") .. "'"
end

--- Resolve asm/gallery directory (app root or parent of love source when tests run from test/).
function M.resolveGalleryAsmDir()
  local candidates = {}
  local source = nil
  if love and love.filesystem and love.filesystem.getSource then
    source = love.filesystem.getSource()
  end
  if type(source) == "string" and source ~= "" then
    candidates[#candidates + 1] = joinPath(source, "asm/gallery")
    candidates[#candidates + 1] = joinPath(source, "../asm/gallery")
  end
  candidates[#candidates + 1] = "asm/gallery"
  candidates[#candidates + 1] = "../asm/gallery"

  for _, dir in ipairs(candidates) do
    if fileExists(joinPath(dir, "Makefile")) then
      return dir
    end
  end
  return nil, "asm/gallery not found (Makefile missing)"
end

function M.collectPackedSketches(wm, sketchWindows)
  local list = {}
  if type(sketchWindows) == "table" and #sketchWindows > 0 then
    for _, win in ipairs(sketchWindows) do
      if WindowCaps.isSketchCanvas(win)
        and not win._closed
        and SketchCanvasPackController.hasPackData(win)
      then
        list[#list + 1] = win
      end
    end
    return list
  end

  if not wm then
    return list
  end
  local windows = wm.windows or wm._windows
  if type(windows) ~= "table" then
    return list
  end
  for _, win in ipairs(windows) do
    if WindowCaps.isSketchCanvas(win)
      and not win._closed
      and SketchCanvasPackController.hasPackData(win)
    then
      list[#list + 1] = win
    end
  end
  return list
end

function M.writeSlideMeta(path, slideCount)
  local n = math.floor(tonumber(slideCount) or 0)
  if n < 1 then
    n = 1
  elseif n > M.MAX_SLIDES then
    n = M.MAX_SLIDES
  end
  local body = table.concat({
    "; Generated by PPUX gallery export - do not edit by hand.",
    ".export slide_count",
    "",
    '.segment "RODATA"',
    "slide_count:",
    string.format("  .byte %d", n),
    "",
  }, "\n")
  return SketchCanvasExportController.writeBinaryFile(path, body)
end

local function ensureDir(path)
  -- Best-effort mkdir -p (POSIX).
  os.execute("mkdir -p " .. shellQuote(path))
end

function M.writeSlideAssets(asmDir, sketches)
  if type(asmDir) ~= "string" or asmDir == "" then
    return false, "missing asm dir"
  end
  if type(sketches) ~= "table" or #sketches < 1 then
    return false, "no packed sketch canvases"
  end
  if #sketches > M.MAX_SLIDES then
    return false, string.format("at most %d sketch canvases (got %d)", M.MAX_SLIDES, #sketches)
  end

  local chrDir = joinPath(asmDir, "data/chr")
  local namDir = joinPath(asmDir, "data/nam")
  ensureDir(chrDir)
  ensureDir(namDir)

  for i, win in ipairs(sketches) do
    local chr4k, chrErr = SketchCanvasExportController.encodeChrBankFromSketch(win)
    if not chr4k then
      return false, string.format("slide %d CHR: %s", i - 1, tostring(chrErr))
    end
    local chr8k, padErr = SketchCanvasExportController.padChrBankTo8KiB(chr4k)
    if not chr8k then
      return false, string.format("slide %d pad: %s", i - 1, tostring(padErr))
    end
    local nam, namErr = SketchCanvasExportController.encodeNametableFromSketch(win, {
      includeAttributes = true,
    })
    if not nam then
      return false, string.format("slide %d nametable: %s", i - 1, tostring(namErr))
    end

    local stem = string.format("slide%02d", i - 1)
    local okChr, errChr = SketchCanvasExportController.writeBinaryFile(
      joinPath(chrDir, stem .. ".chr"),
      chr8k
    )
    if not okChr then
      return false, errChr
    end
    local okNam, errNam = SketchCanvasExportController.writeBinaryFile(
      joinPath(namDir, stem .. ".nam"),
      nam
    )
    if not okNam then
      return false, errNam
    end
  end

  -- Keep unused slots as zeros so CHR segments stay valid.
  local emptyChr = string.rep("\0", SketchCanvasExportController.CHR_BANK_8K)
  local emptyNam = string.rep("\0", SketchCanvasExportController.NAMETABLE_FULL)
  for i = #sketches, M.MAX_SLIDES - 1 do
    local stem = string.format("slide%02d", i)
    local okChr, errChr = SketchCanvasExportController.writeBinaryFile(
      joinPath(chrDir, stem .. ".chr"),
      emptyChr
    )
    if not okChr then
      return false, errChr
    end
    local okNam, errNam = SketchCanvasExportController.writeBinaryFile(
      joinPath(namDir, stem .. ".nam"),
      emptyNam
    )
    if not okNam then
      return false, errNam
    end
  end

  return true, #sketches
end

local function runMake(asmDir)
  -- Always clean first: .incbin data can change without touching .s timestamps.
  local cmd = "make -C " .. shellQuote(asmDir) .. " clean all"
  local result = os.execute(cmd)
  -- Lua 5.1/LuaJIT: returns exit status (0 = success) or true.
  if result == true or result == 0 then
    return true
  end
  return false, "make failed (" .. tostring(result) .. "): " .. cmd
end

local function defaultOutPath(app)
  local dir = SketchCanvasExportController.defaultExportDir(app)
  local stem = "gallery"
  local romPath = app and app.appEditState and app.appEditState.romOriginalPath
  if type(romPath) == "string" and romPath ~= "" then
    local base = romPath:match("([^/\\]+)$") or "rom.nes"
    stem = (base:gsub("%.[^%.]+$", "")):gsub("_edited$", "") .. "_gallery"
  end
  return joinPath(dir, stem .. ".nes")
end

local function copyFile(src, dst)
  local inFh, inErr = io.open(src, "rb")
  if not inFh then
    return false, inErr or "open source failed"
  end
  local data = inFh:read("*a")
  inFh:close()
  return SketchCanvasExportController.writeBinaryFile(dst, data)
end

--- Build gallery ROM from packed sketch windows.
--  opts.asmDir — override asm/gallery path
--  opts.outPath — override output .nes path
--  opts.skipMake — write assets only (tests)
--  @return ok, pathOrErr
function M.buildGalleryRom(app, sketchWindows, opts)
  opts = opts or {}
  local wm = app and app.wm
  if type(wm) == "function" then
    wm = wm()
  end

  local sketches = M.collectPackedSketches(wm, sketchWindows)
  if #sketches < 1 then
    return false, "no packed sketch canvases"
  end
  if #sketches > M.MAX_SLIDES then
    return false, string.format("at most %d sketch canvases (got %d)", M.MAX_SLIDES, #sketches)
  end

  local asmDir, asmErr = opts.asmDir, nil
  if not asmDir then
    asmDir, asmErr = M.resolveGalleryAsmDir()
  end
  if not asmDir then
    return false, asmErr or "asm/gallery not found"
  end

  local okAssets, countOrErr = M.writeSlideAssets(asmDir, sketches)
  if not okAssets then
    return false, countOrErr
  end

  local metaPath = joinPath(asmDir, "s/slide_meta.s")
  local okMeta, metaErr = M.writeSlideMeta(metaPath, countOrErr)
  if not okMeta then
    return false, metaErr
  end

  if opts.skipMake then
    return true, asmDir
  end

  local okMake, makeErr = runMake(asmDir)
  if not okMake then
    return false, makeErr
  end

  local built = joinPath(asmDir, "gallery.nes")
  if not fileExists(built) then
    return false, "make succeeded but gallery.nes missing"
  end

  local outPath = opts.outPath or defaultOutPath(app)
  local okCopy, copyErr = copyFile(built, outPath)
  if not okCopy then
    return false, copyErr
  end
  return true, outPath
end

return M
