-- Single require for scenario builder chunks (common + helpers bindings).

local C = require("test.e2e_visible.scenarios.common")
local H = require("test.e2e_visible.scenarios.helpers")

return {
  BubbleExample = C.BubbleExample,
  PaletteLinkController = C.PaletteLinkController,
  ContextualMenuController = C.ContextualMenuController,
  images = C.images,
  normalizeSpeedMultiplier = C.normalizeSpeedMultiplier,
  pause = C.pause,
  moveTo = C.moveTo,
  mouseDown = C.mouseDown,
  mouseUp = C.mouseUp,
  keyPress = C.keyPress,
  textInput = C.textInput,
  call = C.call,
  assertDelay = C.assertDelay,
  appendClick = C.appendClick,
  appendDrag = C.appendDrag,
  newWindowOptionCenter = C.newWindowOptionCenter,
  newWindowOptionCenterByText = C.newWindowOptionCenterByText,
  newWindowModeToggleCenter = C.newWindowModeToggleCenter,
  textFieldDemoFieldCenter = C.textFieldDemoFieldCenter,
  textFieldDemoFieldTextPoint = C.textFieldDemoFieldTextPoint,
  spriteItemCenter = C.spriteItemCenter,
  toolbarLinkHandleCenter = C.toolbarLinkHandleCenter,
  windowHeaderCenter = C.windowHeaderCenter,
  saveOptionCenter = C.saveOptionCenter,
  menuRowCenter = C.menuRowCenter,
  taskbarRootMenu = C.taskbarRootMenu,
  childMenuRowCenter = C.childMenuRowCenter,
  rootMenuItemCenter = C.rootMenuItemCenter,
  resizeHandleCenter = C.resizeHandleCenter,
  taskbarMenuGapPoint = C.taskbarMenuGapPoint,
  assertTaskbarChildState = C.assertTaskbarChildState,
  buttonCenter = H.buttonCenter,
  appQuickButtonCenter = H.appQuickButtonCenter,
  ppuToolbarButtonCenter = H.ppuToolbarButtonCenter,
  menuRowCenterByText = H.menuRowCenterByText,
  setFocusedTextFieldValue = H.setFocusedTextFieldValue,
  setupDeterministicPpuFixture = H.setupDeterministicPpuFixture,
  harnessHoldShiftForGridResize = H.harnessHoldShiftForGridResize,
  assertStatusContainsOccupiedLayout = H.assertStatusContainsOccupiedLayout,
}
