return {
  currentBank = 1,
  currentColor = 1,
  edits = {
    banks = {
    }
  },
  focusedWindowId = "animation_1",
  kind = "project",
  projectVersion = 1,
  skipOverwriteConfirm = false,
  syncDuplicateTiles = false,
  windowOrderIds = {
    [1] = "bank",
    [2] = "animation_1",
    [3] = "animation_2",
    [4] = "static_art_9",
    [5] = "static_art_2",
    [6] = "static_art_1",
    [7] = "static_art_8",
    [8] = "static_art_3",
    [9] = "static_art_5",
    [10] = "static_art_7",
    [11] = "static_art_6",
    [12] = "static_art_4",
    [13] = "palette_1",
    [14] = "palette_01",
    [15] = "palette_3",
    [16] = "palette_2"
  },
  windows = {
    [1] = {
      activeLayer = 2,
      alwaysOnTop = false,
      cellH = 8,
      cellW = 8,
      collapsed = false,
      cols = 4,
      id = "animation_2",
      kind = "animation",
      layers = {
        [1] = {
          items = {
            [1] = { bank = 1, mirrorX = true, tile = 161, x = 16, y = 16 },
            [2] = { bank = 1, mirrorX = true, tile = 163, x = 16, y = 24 },
            [3] = { bank = 1, mirrorX = true, tile = 164, x = 8, y = 24 },
            [4] = { bank = 1, mirrorX = true, tile = 160, x = 8, y = 8 },
            [5] = { bank = 1, mirrorX = true, tile = 162, x = 8, y = 16 }
          },
          kind = "sprite",
          mode = "8x8",
          name = "Frame 1",
          opacity = 1,
          originX = 0,
          originY = 0
        },
        [2] = {
          items = {
            [1] = { bank = 1, mirrorX = true, tile = 166, x = 16, y = 16 },
            [2] = { bank = 1, mirrorX = true, tile = 167, x = 8, y = 16 },
            [3] = { bank = 1, mirrorX = true, tile = 168, x = 16, y = 24 },
            [4] = { bank = 1, mirrorX = true, tile = 169, x = 8, y = 24 },
            [5] = { bank = 1, mirrorX = true, tile = 165, x = 8, y = 8 }
          },
          kind = "sprite",
          mode = "8x8",
          name = "Frame 2",
          opacity = 1,
          originX = 0,
          originY = 0
        }
      },
      minimized = false,
      mirrorXPreview = false,
      nonActiveLayerOpacity = 0,
      rows = 5,
      scrollCol = 0,
      scrollRow = 0,
      showGrid = "chess",
      title = "Koopa walking",
      visibleCols = 4,
      visibleRows = 5,
      x = 255,
      y = 30,
      z = 10,
      zoom = 2
    },
    [2] = {
      activeLayer = 1,
      alwaysOnTop = false,
      cellH = 8,
      cellW = 8,
      collapsed = false,
      cols = 4,
      id = "static_art_9",
      kind = "static_art",
      layers = {
        [1] = {
          items = {
            [1] = { bank = 1, tile = 118, x = 8, y = 8 },
            [2] = { bank = 1, tile = 119, x = 16, y = 8 },
            [3] = { bank = 1, tile = 120, x = 8, y = 16 },
            [4] = { bank = 1, tile = 121, x = 16, y = 16 }
          },
          kind = "sprite",
          mode = "8x8",
          name = "Layer 1",
          opacity = 1,
          originX = 0,
          originY = 0
        }
      },
      minimized = false,
      mirrorXPreview = false,
      nonActiveLayerOpacity = 1,
      rows = 4,
      scrollCol = 0,
      scrollRow = 0,
      showGrid = "chess",
      title = "Power-up mushroom",
      visibleCols = 4,
      visibleRows = 4,
      x = 451,
      y = 128,
      z = 20,
      zoom = 2
    },
    [3] = {
      activeLayer = 1,
      alwaysOnTop = false,
      cellH = 8,
      cellW = 8,
      collapsed = false,
      cols = 4,
      id = "static_art_1",
      kind = "static_art",
      layers = {
        [1] = {
          items = {
            [1] = { bank = 1, col = 1, row = 1, tile = 325 },
            [2] = { bank = 1, col = 2, row = 1, tile = 325 },
            [3] = { bank = 1, col = 1, row = 2, tile = 327 },
            [4] = { bank = 1, col = 2, row = 2, tile = 327 }
          },
          kind = "tile",
          name = "Layer 1",
          opacity = 1
        }
      },
      minimized = false,
      mirrorXPreview = false,
      nonActiveLayerOpacity = 1,
      rows = 4,
      scrollCol = 0,
      scrollRow = 0,
      showGrid = "chess",
      title = "Brick block",
      visibleCols = 4,
      visibleRows = 4,
      x = 172,
      y = 231,
      z = 30,
      zoom = 2
    },
    [4] = {
      activeLayer = 1,
      alwaysOnTop = false,
      cellH = 8,
      cellW = 8,
      collapsed = false,
      cols = 4,
      id = "static_art_4",
      kind = "static_art",
      layers = {
        [1] = {
          items = {
            [1] = { bank = 1, col = 1, row = 1, tile = 339 },
            [2] = { bank = 1, col = 2, row = 1, tile = 340 },
            [3] = { bank = 1, col = 1, row = 2, tile = 341 },
            [4] = { bank = 1, col = 2, row = 2, tile = 342 }
          },
          kind = "tile",
          name = "Layer 1",
          opacity = 1
        }
      },
      minimized = false,
      mirrorXPreview = false,
      nonActiveLayerOpacity = 1,
      rows = 4,
      scrollCol = 0,
      scrollRow = 0,
      showGrid = "chess",
      title = "Question mark block",
      visibleCols = 4,
      visibleRows = 4,
      x = 258,
      y = 137,
      z = 40,
      zoom = 2
    },
    [5] = {
      activeLayer = 1,
      alwaysOnTop = false,
      cellH = 8,
      cellW = 8,
      collapsed = false,
      cols = 6,
      id = "static_art_3",
      kind = "static_art",
      layers = {
        [1] = {
          items = {
            [1] = { bank = 1, col = 2, row = 1, tile = 310 },
            [2] = { bank = 1, col = 3, row = 1, tile = 311 },
            [3] = { bank = 1, col = 1, row = 2, tile = 309 },
            [4] = { bank = 1, col = 2, row = 2, tile = 293 },
            [5] = { bank = 1, col = 3, row = 2, tile = 293 },
            [6] = { bank = 1, col = 4, row = 2, tile = 312 },
            [7] = { bank = 1, col = 1, row = 3, tile = 313 },
            [8] = { bank = 1, col = 2, row = 3, tile = 314 },
            [9] = { bank = 1, col = 3, row = 3, tile = 315 },
            [10] = { bank = 1, col = 4, row = 3, tile = 316 }
          },
          kind = "tile",
          name = "Layer 1",
          opacity = 1
        }
      },
      minimized = false,
      mirrorXPreview = false,
      nonActiveLayerOpacity = 1,
      rows = 5,
      scrollCol = 0,
      scrollRow = 0,
      showGrid = "chess",
      title = "Cloud/Bush",
      visibleCols = 6,
      visibleRows = 5,
      x = 338,
      y = 34,
      z = 50,
      zoom = 2
    },
    [6] = {
      activeLayer = 1,
      alwaysOnTop = false,
      cellH = 8,
      cellW = 8,
      collapsed = false,
      cols = 6,
      id = "static_art_6",
      kind = "static_art",
      layers = {
        [1] = {
          items = {
            [1] = { bank = 1, col = 1, row = 1, tile = 352 },
            [2] = { bank = 1, col = 2, row = 1, tile = 353 },
            [3] = { bank = 1, col = 3, row = 1, tile = 354 },
            [4] = { bank = 1, col = 4, row = 1, tile = 355 },
            [5] = { bank = 1, col = 1, row = 2, tile = 356 },
            [6] = { bank = 1, col = 2, row = 2, tile = 357 },
            [7] = { bank = 1, col = 3, row = 2, tile = 358 },
            [8] = { bank = 1, col = 4, row = 2, tile = 359 },
            [9] = { bank = 1, col = 1, row = 3, tile = 360 },
            [10] = { bank = 1, col = 2, row = 3, tile = 361 },
            [11] = { bank = 1, col = 3, row = 3, tile = 294 },
            [12] = { bank = 1, col = 4, row = 3, tile = 362 },
            [13] = { bank = 1, col = 1, row = 4, tile = 360 },
            [14] = { bank = 1, col = 2, row = 4, tile = 361 },
            [15] = { bank = 1, col = 3, row = 4, tile = 294 },
            [16] = { bank = 1, col = 4, row = 4, tile = 362 },
            [17] = { bank = 1, col = 1, row = 5, tile = 360 },
            [18] = { bank = 1, col = 2, row = 5, tile = 361 },
            [19] = { bank = 1, col = 3, row = 5, tile = 294 },
            [20] = { bank = 1, col = 4, row = 5, tile = 362 }
          },
          kind = "tile",
          name = "Layer 1",
          opacity = 1
        }
      },
      minimized = false,
      mirrorXPreview = false,
      nonActiveLayerOpacity = 1,
      rows = 6,
      scrollCol = 0,
      scrollRow = 0,
      showGrid = "chess",
      title = "Pipe vertical",
      visibleCols = 6,
      visibleRows = 6,
      x = 340,
      y = 142,
      z = 60,
      zoom = 2
    },
    [7] = {
      activeLayer = 1,
      alwaysOnTop = false,
      cellH = 8,
      cellW = 8,
      collapsed = false,
      cols = 6,
      id = "static_art_7",
      kind = "static_art",
      layers = {
        [1] = {
          items = {
            [1] = { bank = 1, col = 2, row = 0, tile = 305 },
            [2] = { bank = 1, col = 3, row = 0, tile = 306 },
            [3] = { bank = 1, col = 1, row = 1, tile = 304 },
            [4] = { bank = 1, col = 2, row = 1, tile = 294 },
            [5] = { bank = 1, col = 3, row = 1, tile = 308 },
            [6] = { bank = 1, col = 4, row = 1, tile = 307 },
            [7] = { bank = 1, col = 0, row = 2, tile = 304 },
            [8] = { bank = 1, col = 1, row = 2, tile = 294 },
            [9] = { bank = 1, col = 2, row = 2, tile = 294 },
            [10] = { bank = 1, col = 3, row = 2, tile = 294 },
            [11] = { bank = 1, col = 4, row = 2, tile = 294 },
            [12] = { bank = 1, col = 5, row = 2, tile = 307 }
          },
          kind = "tile",
          name = "Layer 1",
          opacity = 1
        }
      },
      minimized = false,
      mirrorXPreview = false,
      nonActiveLayerOpacity = 1,
      rows = 3,
      scrollCol = 0,
      scrollRow = 0,
      showGrid = "chess",
      title = "Hill",
      visibleCols = 6,
      visibleRows = 3,
      x = 342,
      y = 265,
      z = 70,
      zoom = 2
    },
    [8] = {
      activeLayer = 1,
      alwaysOnTop = false,
      cellH = 8,
      cellW = 8,
      collapsed = false,
      cols = 4,
      id = "static_art_8",
      kind = "static_art",
      layers = {
        [1] = {
          items = {
            [1] = { bank = 1, col = 1, row = 1, tile = 427 },
            [2] = { bank = 1, col = 2, row = 1, tile = 429 },
            [3] = { bank = 1, col = 1, row = 2, tile = 428 },
            [4] = { bank = 1, col = 2, row = 2, tile = 430 }
          },
          kind = "tile",
          name = "Layer 1",
          opacity = 1
        }
      },
      minimized = false,
      mirrorXPreview = false,
      nonActiveLayerOpacity = 1,
      rows = 4,
      scrollCol = 0,
      scrollRow = 0,
      showGrid = "chess",
      title = "Cement (?) block",
      visibleCols = 4,
      visibleRows = 4,
      x = 453,
      y = 39,
      z = 80,
      zoom = 2
    },
    [9] = {
      activeLayer = 1,
      alwaysOnTop = false,
      cellH = 8,
      cellW = 8,
      collapsed = false,
      cols = 4,
      id = "static_art_5",
      kind = "static_art",
      layers = {
        [1] = {
          items = {
            [1] = { bank = 1, col = 1, paletteNumber = 4, row = 1, tile = 436 },
            [2] = { bank = 1, col = 2, paletteNumber = 2, row = 1, tile = 437 },
            [3] = { bank = 1, col = 1, row = 2, tile = 438 },
            [4] = { bank = 1, col = 2, row = 2, tile = 439 }
          },
          kind = "tile",
          name = "Layer 1",
          opacity = 1
        }
      },
      minimized = false,
      mirrorXPreview = false,
      nonActiveLayerOpacity = 1,
      rows = 4,
      scrollCol = 0,
      scrollRow = 0,
      showGrid = "chess",
      title = "Ground block",
      visibleCols = 4,
      visibleRows = 4,
      x = 261,
      y = 230,
      z = 90,
      zoom = 2
    },
    [10] = {
      activePalette = true,
      alwaysOnTop = false,
      collapsed = false,
      cols = 4,
      compactView = true,
      id = "palette_1",
      items = {
        [1] = { code = "2C", col = 0, row = 0 },
        [2] = { code = "30", col = 1, row = 0 },
        [3] = { code = "19", col = 2, row = 0 },
        [4] = { code = "0F", col = 3, row = 0 }
      },
      kind = "palette",
      minimized = false,
      mirrorXPreview = false,
      nonActiveLayerOpacity = 1,
      paletteName = "smooth_fbx",
      rows = 1,
      scrollCol = 0,
      scrollRow = 0,
      selectedCol = 3,
      selectedRow = 0,
      showGrid = "chess",
      title = "Day stage BG palette",
      visibleCols = 4,
      visibleRows = 1,
      x = 526,
      y = 55,
      z = 100,
      zoom = 1
    },
    [11] = {
      activePalette = false,
      alwaysOnTop = false,
      collapsed = false,
      cols = 4,
      compactView = true,
      id = "palette_01",
      items = {
        [1] = { code = "0F", col = 0, row = 0 },
        [2] = { code = "16", col = 1, row = 0 },
        [3] = { code = "27", col = 2, row = 0 },
        [4] = { code = "18", col = 3, row = 0 }
      },
      kind = "palette",
      minimized = false,
      mirrorXPreview = false,
      nonActiveLayerOpacity = 1,
      paletteName = "smooth_fbx",
      rows = 1,
      scrollCol = 0,
      scrollRow = 0,
      selectedCol = 2,
      selectedRow = 0,
      showGrid = "none",
      title = "Mario palette",
      visibleCols = 4,
      visibleRows = 1,
      x = 528,
      y = 98,
      z = 110,
      zoom = 1
    },
    [12] = {
      activePalette = false,
      alwaysOnTop = false,
      collapsed = false,
      cols = 4,
      compactView = true,
      id = "palette_2",
      items = {
        [1] = { code = "22", col = 0, row = 0 },
        [2] = { code = "29", col = 1, row = 0 },
        [3] = { code = "1A", col = 2, row = 0 },
        [4] = { code = "0F", col = 3, row = 0 }
      },
      kind = "palette",
      minimized = false,
      mirrorXPreview = false,
      nonActiveLayerOpacity = 1,
      paletteName = "smooth_fbx",
      rows = 1,
      scrollCol = 0,
      scrollRow = 0,
      selectedCol = 0,
      selectedRow = 0,
      showGrid = "chess",
      title = "Pipe green",
      visibleCols = 4,
      visibleRows = 1,
      x = 540,
      y = 148,
      z = 120,
      zoom = 1
    },
    [13] = {
      activePalette = false,
      alwaysOnTop = false,
      collapsed = false,
      cols = 4,
      compactView = true,
      id = "palette_3",
      items = {
        [1] = { code = "07", col = 0, row = 0 },
        [2] = { code = "17", col = 1, row = 0 },
        [3] = { code = "27", col = 2, row = 0 },
        [4] = { code = "36", col = 3, row = 0 }
      },
      kind = "palette",
      minimized = false,
      mirrorXPreview = false,
      nonActiveLayerOpacity = 1,
      paletteName = "smooth_fbx",
      rows = 1,
      scrollCol = 0,
      scrollRow = 0,
      selectedCol = 0,
      selectedRow = 0,
      showGrid = "chess",
      title = "Other",
      visibleCols = 4,
      visibleRows = 1,
      x = 508,
      y = 217,
      z = 130,
      zoom = 1
    },
    [14] = {
      activeLayer = 1,
      alwaysOnTop = false,
      cellH = 8,
      cellW = 8,
      collapsed = false,
      cols = 16,
      currentBank = 1,
      id = "bank",
      kind = "chr",
      layers = {
        [1] = {
          items = {
          },
          name = "Bank 1",
          opacity = 1
        }
      },
      minimized = false,
      mirrorXPreview = false,
      nonActiveLayerOpacity = 1,
      orderMode = "normal",
      rows = 32,
      scrollCol = 0,
      scrollRow = 0,
      showGrid = "lines",
      title = "Bank 1/1",
      visibleCols = 16,
      visibleRows = 32,
      x = 32,
      y = 44,
      z = 140,
      zoom = 1
    },
    [15] = {
      activeLayer = 1,
      alwaysOnTop = false,
      cellH = 8,
      cellW = 8,
      collapsed = false,
      cols = 4,
      id = "static_art_2",
      kind = "static_art",
      layers = {
        [1] = {
          items = {
            [1] = { bank = 1, tile = 55, x = 16, y = 8 },
            [2] = { bank = 1, tile = 58, x = 8, y = 8 },
            [3] = { bank = 1, tile = 79, x = 8, y = 16 },
            [4] = { bank = 1, mirrorX = true, tile = 79, x = 16, y = 16 }
          },
          kind = "sprite",
          mode = "8x8",
          name = "Layer 1",
          opacity = 1,
          originX = 0,
          originY = 0
        }
      },
      minimized = false,
      mirrorXPreview = false,
      nonActiveLayerOpacity = 1,
      rows = 4,
      scrollCol = 0,
      scrollRow = 0,
      showGrid = "chess",
      title = "Small Mario - idle",
      visibleCols = 4,
      visibleRows = 4,
      x = 170,
      y = 36,
      z = 150,
      zoom = 2
    },
    [16] = {
      activeLayer = 1,
      alwaysOnTop = false,
      cellH = 8,
      cellW = 8,
      collapsed = false,
      cols = 4,
      id = "animation_1",
      kind = "animation",
      layers = {
        [1] = {
          items = {
            [1] = { bank = 1, tile = 112, x = 8, y = 8 },
            [2] = { bank = 1, tile = 113, x = 16, y = 8 },
            [3] = { bank = 1, tile = 114, x = 8, y = 16 },
            [4] = { bank = 1, tile = 115, x = 16, y = 16 }
          },
          kind = "sprite",
          mode = "8x8",
          name = "Frame 1",
          opacity = 1,
          originX = 0,
          originY = 0
        },
        [2] = {
          items = {
            [1] = { bank = 1, tile = 112, x = 8, y = 8 },
            [2] = { bank = 1, tile = 113, x = 16, y = 8 },
            [3] = { bank = 1, mirrorX = true, tile = 115, x = 8, y = 16 },
            [4] = { bank = 1, mirrorX = true, tile = 114, x = 16, y = 16 }
          },
          kind = "sprite",
          mode = "8x8",
          name = "Frame 2",
          opacity = 1,
          originX = 0,
          originY = 0
        }
      },
      minimized = false,
      mirrorXPreview = false,
      nonActiveLayerOpacity = 0,
      rows = 4,
      scrollCol = 0,
      scrollRow = 0,
      showGrid = "chess",
      title = "Goomba walking",
      visibleCols = 4,
      visibleRows = 4,
      x = 170,
      y = 137,
      z = 160,
      zoom = 2
    }
  }
}
