; Generated by PPUX gallery export - do not edit by hand.
.export slide_count, fade_hold, use_transitions, show_first_once

.segment "RODATA"
slide_count:
  .byte 1
fade_hold:
  .byte 6
use_transitions:
  .byte 1
show_first_once:
  .byte 0
