-- Generated by tools/extract_hue_ramp.py — do not edit by hand.
-- Source: assets/hue_ramp.png (8x1), 8 stops along sample row.
return {
  0.0, -- col 1 x=0 #cb2222 rgb(203,34,34)
  0.0956607495, -- col 2 x=1 #cb8322 rgb(203,131,34)
  0.1627218935, -- col 3 x=2 #cbc722 rgb(203,199,34)
  0.2721893491, -- col 4 x=3 #60cb22 rgb(96,203,34)
  0.5108481262, -- col 5 x=4 #22c0cb rgb(34,192,203)
  0.6025641026, -- col 6 x=5 #2263cb rgb(34, 113, 203)
  0.7238658777, -- col 7 x=6 #5c22cb rgb(92,34,203)
  0.7909270217 -- col 8 x=7 #a022cb rgb(160,34,203)
}
